### PR TITLE
latest changes, pull at your leisure

### PR DESCRIPTION
**Pull request by keflavich**

### CODE REVIEW

**Comment by keflavich** [comment]
ks_vs_angsep_normalized_histograms_btop150
ks_vs_angsep_normalized_histograms_btop200
ks_vs_angsep_normalized_histograms_btop350
ks_vs_angsep_normalized_histograms_runi180

**Comment by keflavich** [comment]
With power-law fitting, it looks like there's not _so_ much scatter (still, not negligible), at least for the external feedback runs, but there is definitely time evolution.  More scatter in the feedback run.

powerlaw_alpha_vs_ks_btop100
powerlaw_alpha_vs_ks_btop150
powerlaw_alpha_vs_ks_btop200
powerlaw_alpha_vs_ks_btop350
powerlaw_alpha_vs_ks_runi180

**Comment by jimdale** [comment]
so, wait - which dumps do these plots belong to? the filenames aren’t very helpful ;)

**Comment by keflavich** [comment]
ach, annoying, they got renamed.  I guess we should add the simulation name in the titles.  The one that is different is run I

**Pull request merged**
